network:
  task: sdf
  final_activation: tanh
data loading:
  batch size: 64
  subset: balls
  number of objects:
  - 2
  - 4
  max radius: 0.5
  dataset: sdf_synthetic
  input discretization:
    type: rqmc
    sample points: 4096
optimizer:
  type: AdamW
  learning rate: 0.1
  max steps: 1000
